### ISSUE TITLE
Build Out Testnet Behavioral  Simulation Testing

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda-automation#10]
We need to build out some code that will allow us to "watch" a testnet and verify things are happing as they should. Ideally, most of this information would be collected from the logs, however we can also retrieve lots of useful information from the individual daemon GraphQL Endpoints. 

Architecture: 
- Kibana C&C Dashboard
- Log Collectors on Nodes
- Ansible Scripts for Triggering and collecting data about behaviors
  - Output events to ElasticSearch for display on dashboard

Behaviors: 
- Sending a transaction from one wallet to another
- Early Joins
  - Sleep Until Genesis
- Late Joins
- Node Restarts
- Delegation
- Staking

Tests: 
- Verify Block rewards going to a wallet
- Verify Snarking fees going to a wallet 
- Verify Delegation Transactions/Payouts
- Verify Daemons log output appropriately
- Identify changes as max nAccounts increases

**Comment by yourbuddyconner** [comment]
On sending a transaction: 
The basic workflow for sending a transaction works like this: Send a Payment, Listen for new blocks until your transaction makes it into one, wait for that block to pass the confirmation threshold to be considered permanent. 

Sending payments is available in the GraphQL API, but currently GraphQL Subscriptions arent 100% implemented meaning we still have to poll the daemon to get new blocks.

**Comment by yourbuddyconner** [comment]
I would like to be able to run behavioral tests locally as I am developing them. However, there is currently a limitation where a Coda Daemon's ports must be publicly-addressable. 

Right now the Coda Daemon is not configured to set up port forwarding via UPNP, but @jkrauska has mentioned that there is a plan in the works to implement LibP2P features that would enable this. 

Failing LibP2P handling this, we can probably get away with using the [upnpc utility](http://manpages.ubuntu.com/manpages/xenial/man1/upnpc.1.html) in the short-term to set up this port forwarding.

Issues that discuss this: 
- https://github.com/CodaProtocol/coda/issues/860

**Comment by yourbuddyconner** [comment]
From @nholland94: 
```
We also need to run the following test in order to determine the ledger depth we need for beta:
- continously create new accounts on the network
- concurrently, continously restart a couple of nodes and measure bootstrap success and time it takes to complete (specifically, measuring the time it takes to download the epoch ledgers -- we may need to add logs for you to measure that)
- eventually, nodes will not be able to bootstrap within a slot (however, some failures will start before then due to slot barriers)
```
