### ISSUE TITLE
Move Node Provisioning Code to Terraform

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda-automation#14]
We do a lot of stuff during the Ansible run that could be easily achieved in `user_data.sh` script passed to EC2 servers at runtime. 

- Coda Installation
- Filebeat/Metricbeat Installation
- SSH Key Installation

**Comment by yourbuddyconner** [comment]
The coda installation step was moved to terraform, it is present in the user-data script here: https://github.com/CodaProtocol/coda-automation/blob/master/terraform/modules/coda-node/main.tf#L50-L53

**Comment by jkrauska** [comment]
Lets add some of the other things from ansible.
(monit, carbon, testnet-config?)

**Comment by bkase** [comment]
Closing for now because for testnet deploys we want the flexibility of our releases being messed up -- and we release hotfixes
