### ISSUE TITLE
Expand codalib.py script into legit Python library

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda-automation#18]
The work being done in the `scripts/codalib.py` file is really solid, we should expand on it and allow it to be distributed to end users wishing to script against the Coda Daemon. 

Ideally we would be able to run the library against both a remote daemon and a local daemon process, meaning we would utilize the Daemon's GraphQL Endpoints (see #15). That said, in the short term scripting against the CLI for a local daemon will be sufficient.

**Comment by yourbuddyconner** [comment]
Barriers to implementation: 
- Currently proposers in a test net are started with the `-proposer-key` CLI argument. However, this does not configure the key for use with a wallet internally. This prevents us from easily scripting transactions. The desired solution is to have a graphQL Endpoint that can import a private key into the wallet. 

[Issue Link](https://www.notion.so/codaprotocol/GraphQL-Mutation-import-of-pre-existing-wallets-private-keys-4f922416676f4b1bb095e50214fe7bce)

**Comment by yourbuddyconner** [comment]
Talked to the product team, @o1pranay says it's reasonable to see these things get implemented in the next 2-3 weeks.

**Comment by o1pranay** [comment]
it's on our radar, we'll try and scope these into an upcoming sprint.  The status endpoint in graphql is straightforward, but re: the import sk work, ideally would like to time it with the UI work as well

**Comment by yourbuddyconner** [comment]
These two asks were completed this sprint so this is actionable. 

Created a library here: https://github.com/CodaProtocol/coda-python-client
Will be making a PR to this repo to incorporate the new library.

**Comment by yourbuddyconner** [comment]
Steps: 
- Add `requirements.txt` to the scripts repository
- Prune scripts directory to things that are currently being used in the TestNet 
- Update scripts to use the CodaClient library.

**Comment by jkrauska** [comment]
Update scripts to use the CodaClient library.
