### ISSUE TITLE
Design strategy for managing ElasticSearch data

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda-automation#20]
One of the major complaints that people on the internet like to bring up about the AWS ElasticSearch service is that deployments are pretty static once they're set up. Improvements have been made, like the addition of the ability to update clusters in place, but it's definitely better to think about a cluster as "ephemeral." 

As such, we should have a strategy to archive data from an elasticsearch cluster before it gets torn down. In addition, if we can archive the indices, we should also be able to easily load them into new dynamically-created clusters. 

In practice, this will look like a data migration step where data is loaded into elasticsearch once terraform has completed its setup process. 

I think this could probably be accomplished entirely with the ElasticSearch Curator project which can be read about here: https://www.elastic.co/guide/en/elasticsearch/client/curator/current/about-features.html

**Comment by yourbuddyconner** [comment]
Lets build a forecast for how much this will cost long-term.

**Comment by bkase** [comment]
This should be a lambda-cron
