### ISSUE TITLE
Investigate AWS Secrets Manager for Secrets Storage

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda-automation#24]
Since we have to pull secrets out of the repo, we should use a service to store them. I think SSM is a good choice because we can use it for Terraform and/or Ansible deployments on any cloud provider. 

For example, we could use this to store IP Addresses for whitelisting without storing them in the Terraform source code. 

Terraform:
https://www.terraform.io/docs/providers/aws/r/ssm_parameter.html
https://www.terraform.io/docs/providers/aws/d/ssm_parameter.html
Ansible: 
https://docs.ansible.com/ansible/latest/plugins/lookup/aws_ssm.html

**Comment by jkrauska** [comment]
ssm is neat, but a big buy in..   we just need a simple way to store two short lists.  I think ansible vault can do this pretty easily without all the other whistles.

**Comment by yourbuddyconner** [comment]
Done in #3
