### ISSUE TITLE
[Leaderboard] Automate leaderboard metrics

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda-automation#259]
There is a need to regularly retrieve data about the blockchain and use it to update the Coda Testnet Leaderboard. The challenges vary in terms of when/how metrics are counted for points, so the collection can be a little tricky. 

High-Level Requirements: 
- Support collecting metrics that aggregate all observed blocks in the chain
- Support collecting metrics that aggregate only blocks that are part of the "canonical" blockchain
- Support collecting metrics that aggregate only blocks that were produced during a "Magic Window" 
- Support collecting metrics that aggregate only blocks on the "canonical" blockchain that were produced during a "Magic Hour"

**Comment by yourbuddyconner** [comment]
Related to #253

**Comment by bkase** [comment]
Please run the lambda function daily (at least, maybe twice a day)

**Comment by yourbuddyconner** [comment]
Plugged in with @Schmavery's uploader code and everything mostly works. However, we should probably use "service account" credentials as opposed to using the InstalledAppFlow which is being used currently:
https://google-auth.readthedocs.io/en/latest/user-guide.html

This is mostly due to the fact this runs as a daemon process without human interference, and thus the oauth flow doesnt fit this model.

**Comment by yourbuddyconner** [comment]
Got the service account working, just need to work on deployment.
