### ISSUE TITLE
Libp2p peer list on a fresh network (resolve libp2p ux)

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda-automation#283]
The new LibP2P update introduces some new metadata requirements for connecting to nodes in the peer network. To facilitate dynamic configuration of nodes (and avoid having to bake the seed peers into the wallet/daemon every release) we should set up an endpoint that will facilitate the retrieval of this data at runtime. 

I am imagining a payload structure like this: 

```
{
  "TestnetName": {
    "seeds": [
        "/ip4/52.39.56.50/tcp/8303/ipfs/12D3KooWHMmfuS9DmmK9eH4GC31arDhbtHEBQzX6PwPtQftxzwJs",
        "/ip4/18.212.230.102/tcp/8303/ipfs/12D3KooWAux9MAW1yAdD8gsDbYHmgVjRvdfYkpkfX7AnyGvQaRPF",
        "/ip4/52.13.17.206/tcp/8303/ipfs/12D3KooWCZA4pPWmDAkQf6riDQ3XMRN5k99tCsiRhBAPZCkA8re7"
    ]
  }
}
```

All the data required should be available during the terraform step of our deploy pipeline, which means this could be simply implemented by dumping a JSON file to an s3 bucket.

**Comment by jkrauska** [comment]
add port as that's part of the structure.

we'll also need something to parse and include in bash

I would be inclined to also include bash-helper: """ -peer /ip4/... ... ... """ in the json.
