### ISSUE TITLE
Crash daemon when transfer keys

### ISSUE THREAD

**Issue by Igor-Tselkovskiy** [CodaProtocol/coda-automation#314]
Copy keys with 1 server to 2 . If start daemon he i crash
[coda_short.log](https://github.com/CodaProtocol/coda-automation/files/3872108/coda_short.log)

**Comment by bkase** [comment]
Looks like it's from:

`Secret_box.of_yojson (Yojson.Safe.from_string file_contents)` in secret_file.ml line 127

and the error "Blank input data" probably means the file is either empty or has the wrong permissions.

We should definitely make a better error message here, but there's probably something wrong with the permissions on your private key file

**Comment by Igor-Tselkovskiy** [comment]
![Screenshot from 2019-11-21 03-32-46](https://user-images.githubusercontent.com/57884194/69290069-b80b1c00-0c0f-11ea-9e65-57f6fd23fa6c.png)

**Comment by Igor-Tselkovskiy** [comment]
restart 5 time and worked =/
