### ISSUE TITLE
Audit Coda Logs and Determine Usability in Monitoring

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda-automation#32]
We should look deeply into the Coda logs and attempt to enumerate all the different kinds and additionally what the logs can be used for. 

Ideally, every log that coda produces at the `INFO` log-level will be directly applicable to some portion of a TestNet dashboard. Anything that is not useful should only be displayed in the `DEBUG` log level, so we can worry less about indexing unnecessary data.

**Comment by bkase** [comment]
This is deprecated by prometheus right?

**Comment by yourbuddyconner** [comment]
@bkase Yes and no. There's plenty of information that doesn't map 100% to metrics that is appropriate to expose in logs.

That said, I would prioritize complete metrics coverage over anything log-related for the time being.

**Comment by yourbuddyconner** [comment]
Related to CodaProtocol/coda#2800

**Comment by bkase** [comment]
Proposal:

Conner + Nathan to produce action items for logs

(look at log volume per message type, go after high noise ones)
