### ISSUE TITLE
Build TestNet Requirements

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda-automation#46]
# TestNet Components
These are the components a Coda Network relies on. 

## Genesis Timestamp
This is a time (usually in the future) in which the Genesis Block will be created. In a Production Network, it is hard-coded to some point in the future and nodes will have to wait until the specified time to connect. 

In TestNets, we have the option to use a "time-offset" where the Genesis Block was created some time in the past, this allows us to dynamically create Coda Networks at arbitrary times without rebuilding.

## Genesis Private/Public Keys
Currently we are loading keys from the Genesis Ledger via flat files that are committed to the repo. 

Going forward, the best way to manage these keys is for them to be stored in one file, organized by a unique identifier hash of some kind, and (optionally) distributed to hosts at Terraform-time. This will allow for more deterministic and predictable TestNet builds. 

Ultimately, I think we should refrain from loading keys from the Genesis Ledger on test net nodes at all, and instead have the Daemons create new wallets and feed them with the Faucet. Genesis Keys should be considered high-value assets in the long-term. 

## Proving Keys
These are generated at compile time, same as the Genesis Keys. Currently, these get sent to Google Cloud's S3 equivalent. 

These should end up in Artifactory and fronted by a CDN for DDoS Protection. 

## Daemon Artifacts
These are (obviously) generated at compile time. Right now they are being sent to S3. 

We should send them to Artifactory for every build, and attach them to Github Releases as an additional (manual) step. 

# Testnet Services
These are services that do not strictly belong to the protocol itself, but O(1) will operate to add value to test networks. They typically will present an HTTP interface that proxies requests to a Coda Daemon. 

## Faucet Service
Right now there is no formalized Faucet, we have just been delegating an individual to do Faucet duties.

This practice is unsustainable as we scale and create many testnets, as such we need to have an off-chain process that can do this work. It can consist of a Flask App that just creates a subprocess call to the CLI.

## Echo Service
This will be a service that will send back any Coda that is sent to it, allowing users on the network to test out sending and receiving transactions. 

## Uptime Service
This service will serve as a courtesy/sanity check to our users. It will simply check if the Coda Client ports are open/active for the requested host. It should also have the capacity to do this check for an arbitrary number of hosts on a scheduled interval, and optionally alert the Node Operators in question of downtime.

**Comment by yourbuddyconner** [comment]
# Starting a TestNet
A Coda Network must be started in a particular order. 

## Seed Node(s)
First, you have to start a Seed Node, and it has to be live for a sufficient amount of time for its processes to start, ~5 seconds. There can be many seed nodes, but a single node must be started first and all others joined using the first seed. 

## Peer Node(s)
Each peer node must be started with a seed node's IP Address as an argument. This enables it to connect to the Seed, collect the peer routing table, and connect to other nodes in the network.

For the purposes of a Test Net, these peer nodes should create new wallets and have their contents funded via a Faucet account. 

## Faucet
Right now there is no formalized Faucet, we have just been delegating an individual to do Faucet duties. 

This practice is unsustainable as we scale and create many testnets, as such we need to have an off-chain process that can do this work. It can consist of a Flask App that just creates subprocess call to the CLI.

**Comment by yourbuddyconner** [comment]
# The Faucet
The Faucet is a really simple piece of machinery. It simply proxies an HTTP request to a local Daemon and returns the Daemon's answer as the response. 

It should be packaged inside a Docker container alongside a Coda Daemon, either in the same container or as a networked sidekick container. 

MVP Functionality Includes: 
- Request Validation 
- Max Transaction Limit (to prevent someone from cleaning the faucet out at once)

Extra Credit: 
- API Keys (useful for rate limiting)

**Comment by yourbuddyconner** [comment]
# The Echo Service
The Echo Service will be functionally very similar to The Faucet. It can optionally present an HTTP API to inspect the service, but it will simply be waiting for transactions to come to its account and then send those funds back to the originating account. 

MVP Functionality Includes: 
- Log that a transaction was received 
- Send back the value of the original received transaction, plus some transaction fee, to the originating account 

Extra Credit: 
- Prometheus Metrics

**Comment by bkase** [comment]
@Schmavery 	is working on consolidating the echo and faucet services since they share most of the same logic -- I believe we'll try to keep it as a monolith for as long as possible which should make maintenance easier
