### ISSUE TITLE
Nightly Testnet

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda-automation#6]
Every 24 hours a new testnet should launch and run for X hours and do Y tasks.

**Comment by yourbuddyconner** [comment]
Product team expressed interest in having a "Daily Testnet" which believe would use this mechanism. At its most basic, we'd like to see a test net spin up for as long as possible (every morning at minimum) that the product team can run their local daemons against. 

Paging: @figitaki @Schmavery @o1pranay @bkase

**Comment by yourbuddyconner** [comment]
Smoke Test exists
