### ISSUE TITLE
Investigate Alarms in Elastic/Grafana

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda-automation#84]
We have logs going to elastic and stats going to grafana.

Investigate alarm triggers and delivery.

eg triggers:
 - forked nodes
 - block production rate -> 0
 - transaction rate -> 0

delivery: 
 - chatops in to #testnet-operations ?
 - pagerduty?

**Comment by yourbuddyconner** [comment]
+1 for pagerduty

**Comment by bkase** [comment]
Vote for chatops for now

**Comment by yourbuddyconner** [comment]
Actionable Testnet Alerts: 
- Current Testnet
  - `Block Rate = 0` for `> 30 minutes`
    - Action: Block Producers are down OR Prometheus is down
  - Abs(`Difference in Observed Block Height`) for one or more node `> 5` for `1 hour` 
    - Action: Block Producer(s) are forked and should be rebooted one at a time until they are synced.

**Comment by yourbuddyconner** [comment]
Set up some alerts, we can revisit this again as more scenarios emerge that need alerts.
